package test;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import test.Score;
import test.QuestionPanel;

public class TriviaGuiController {
	@FXML
	private Pane triviaGuiPanel;
	@FXML
	private Label genre1;
	@FXML
	private Label genre5;
	@FXML
	private Label genre4;
	@FXML
	private Label genre3;
	@FXML
	private Label genre2;
	@FXML
	private Button marvel100;
	@FXML
	private Button marvel200;
	@FXML
	private Button marvel300;
	@FXML
	private Button marvel400;
		
	private Button[] button = new Button[21];
	
	@FXML
	private Button anime100;
	@FXML
	private Button anime200;
	@FXML
	private Button anime300;
	@FXML
	private Button anime400;
	@FXML
	private Button pirates100;
	@FXML
	private Button pirates200;
	@FXML
	private Button pirates300;
	@FXML
	private Button pirates400;
	@FXML
	private Button starwars100;
	@FXML
	private Button starwars200;
	@FXML
	private Button starwars300;
	@FXML
	private Button starwars400;
	@FXML
	private Button fantasy100;
	@FXML
	private Button fantasy200;
	@FXML
	private Button fantasy300;
	@FXML
	private Button fantasy400;
	@FXML
	private Button quitButton;
	@FXML
	private Button newGameButton;
	@FXML
	private Label player2Label;
	@FXML
	private Label player3Label;
	@FXML
	private Label player1Label;
	@FXML
	protected Label playerOneScore;
	@FXML
	protected Label playerTwoScore;
	@FXML
	protected Label playerThreeScore;
	
	private int i=0;
	protected Score scoreBoard;
	static TriviaGuiController game;
	
	public void initialize() {
		button[0] = marvel100;
		button[1] = marvel200;
		button[2] = marvel300;
		button[3] = marvel400;
		button[4] = anime100;
		button[5] = anime200;
		button[6] = anime300;
		button[7] = anime400;
		button[8] = pirates100;
		button[9] = pirates200;
		button[10] = pirates300;
		button[11] = pirates400;
		button[12] = starwars100;
		button[13] = starwars200;
		button[14] = starwars300;
		button[15] = starwars400;
		button[16] = fantasy100;
		button[17] = fantasy200;
		button[18] = fantasy300;
		button[19] = fantasy400;
		scoreBoard = new Score();
		game = new TriviaGuiController();
		
		
	}

	// Event Listener on Button[#marvel100].onAction
	@FXML
	public void openMarvelQuestion1(ActionEvent event) {
		// TODO Autogenerated
		i=0;
		System.out.println(i);
//		try {
//		FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("DefaultQuestionPanel.fxml"));
//		Parent root1;
//			root1 = (Parent) fxmlLoader.load();
//			Stage stage = new Stage();
//			stage.setScene(new Scene(root1)); 
//			stage.show();
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}

		playerOneScore.setText("123");
		button[i].setDisable(true);
		
	}
	// Event Listener on Button[#marvel200].onAction
	@FXML
	public void openMarvelQuestion2(ActionEvent event) {
		// TODO Autogenerated
		i=1;
		System.out.println(i);
		button[i].setDisable(true);
		
	}
	// Event Listener on Button[#marvel300].onAction
	@FXML
	public void openMarvelQuestion3(ActionEvent event) {
		// TODO Autogenerated
		i=2;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#marvel400].onAction
	@FXML
	public void openMarvelQuestion4(ActionEvent event) {
		// TODO Autogenerated
		i=3;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#anime100].onAction
	@FXML
	public void openAnimeQuestion1(ActionEvent event) {
		// TODO Autogenerated
		i=4;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#anime200].onAction
	@FXML
	public void openAnimeQuestion2(ActionEvent event) {
		// TODO Autogenerated
		i=5;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#anime300].onAction
	@FXML
	public void openAnimeQuestion3(ActionEvent event) {
		// TODO Autogenerated
		i=6;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#anime400].onAction
	@FXML
	public void openAnimeQuestion4(ActionEvent event) {
		// TODO Autogenerated
		i=7;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#pirates100].onAction
	@FXML
	public void openPiratesQuestion1(ActionEvent event) {
		// TODO Autogenerated
		i=8;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#pirates200].onAction
	@FXML
	public void openPiratesQuestion2(ActionEvent event) {
		// TODO Autogenerated
		i=9;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#pirates300].onAction
	@FXML
	public void openPiratesQuestion3(ActionEvent event) {
		// TODO Autogenerated
		i=10;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#pirates400].onAction
	@FXML
	public void openPiratesQuestion4(ActionEvent event) {
		// TODO Autogenerated
		i=11;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#starwars100].onAction
	@FXML
	public void openStarWarsQuestion1(ActionEvent event) {
		// TODO Autogenerated
		i=12;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#starwars200].onAction
	@FXML
	public void openStarWarsQuestion2(ActionEvent event) {
		// TODO Autogenerated
		i=13;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#starwars300].onAction
	@FXML
	public void openStarWarsQuestion3(ActionEvent event) {
		// TODO Autogenerated
		i=14;
		System.out.println(i);
		button[i].setDisable(true);
		
	}
	// Event Listener on Button[#starwars400].onAction
	@FXML
	public void openStarWarsQuestion4(ActionEvent event) {
		// TODO Autogenerated
		i=15;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#fantasy100].onAction
	@FXML
	public void openFantasyQuestion1(ActionEvent event) {
		// TODO Autogenerated
		i=16;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#fantasy200].onAction
	@FXML
	public void openFantasyQuestion2(ActionEvent event) {
		// TODO Autogenerated
		i=17;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#fantasy300].onAction
	@FXML
	public void openFantasyQuestion3(ActionEvent event) {
		// TODO Autogenerated
		i=18;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#fantasy400].onAction
	@FXML
	public void openFantasyQuestion4(ActionEvent event) {
		// TODO Autogenerated
		i=19;
		System.out.println(i);
		button[i].setDisable(true);
	}
	// Event Listener on Button[#quitButton].onAction
	@FXML
	public void quitAction(ActionEvent event) {
		// TODO Autogenerated
	    Stage stage = (Stage) quitButton.getScene().getWindow();
	   // // do what you have to do
	    stage.close();
	}
	// Event Listener on Button[#newGameButton].onAction
	@FXML
	public void newGameAction(ActionEvent event) {
		// TODO Autogenerated
		for(i=0;i<20;i++){
			button[i].setDisable(false);
		}
		scoreBoard.clearScore();
		playerOneScore.setText(""+scoreBoard.getplayer1());
		playerTwoScore.setText(""+scoreBoard.getplayer2());
		playerThreeScore.setText(""+scoreBoard.getplayer3());
	}
}
